apiVersion: v1
kind: Secret

metadata:
  name: db-connection
  
type: Opaque

data:
  url: cG9zdGdyZXNxbDovL2RvYWRtaW46QVZOU183LU01bVZtLUtUWGExTHN1S3RKQG5sdy11bml0ZS1kby11c2VyLTYyNzgyOTgtMC5jLmRiLm9uZGlnaXRhbG9jZWFuLmNvbToyNTA2MC9kZWZhdWx0ZGI/c3NsbW9kZT1yZXF1aXJlCg==